### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by rongzhx123** [iamcal/emoji-data#141]
where are the demos show how to use it ?

**Comment by jcubic** [comment]
You can take a look at my [Emoji in Terminal](https://codepen.io/jcubic/pen/qPVMPg)

**Comment by lazamar** [comment]
# How to use the sprites

You create an html element with the sprites sheet as background, set its size to be very big, then move it around to show only the emoji you want.

Emojis have a `sheet_x` and `sheet_y` property, which show its row and column position in the sprite sheet.

Currently the sprite sheet has 52 rows and 52 columns. If we say that each emoji should measure 100% of our html element's size, we can set the background to `5200% 5200%`. 

Here is how we would show the Brazilian flag, which is at position x = 1, y = 10:
  
``` css
#brazilFlag {
    background: url(https://raw.githubusercontent.com/iamcal/emoji-data/master/sheet_google_32.png);
    background-size: 5100% 5100%;
    background-position: calc(1 * 100%/51) calc(10 * 100%/51);
}
```
